version: "3.3"

services:
  db:
    container_name: 'postgres'
    restart: 'always'
    image: 'postgres'
   
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5432:5432'
    networks:
    - 'shared-network'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  
  web:
    container_name: 'codbn'
    restart: 'unless-stopped'
   
    build:
      context: .

    ports:
      - '3000:3000'
    networks:
    - 'shared-network'
    depends_on:
      - db
networks:
  shared-network: